import org.jetbrains.kotlin.gradle.dsl.JvmTarget
import org.jetbrains.kotlin.gradle.tasks.KotlinCompile

plugins {
    id "org.jetbrains.kotlin.jvm" version "2.4.20"
    id "org.jetbrains.kotlin.plugin.spring" version "2.4.20"
    id "org.jetbrains.kotlin.plugin.jpa" version "2.4.20"
    id "application"
    id "org.springframework.boot" version "4.1.1"
    id "io.spring.dependency-management" version "1.1.7"
}

version = "0.1"
group = "no.nav.cv.eures"
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
}

repositories {
    mavenCentral()
    maven { url = "https://github-package-registry-mirror.gc.nav.no/cached/maven-release" }
    maven { url = "https://packages.confluent.io/maven" }
}

ext {
    springdocVersion = '3.1.1'
    set('kotlin.version', '2.4.20')
    tokenSupportVersion = '6.0.13'
}

dependencies {
    implementation "org.jetbrains.kotlin:kotlin-reflect"
    implementation "net.logstash.logback:logstash-logback-encoder:9.0"

    implementation "tools.jackson.module:jackson-module-kotlin"
    implementation "tools.jackson.dataformat:jackson-dataformat-xml"

    runtimeOnly    "org.postgresql:postgresql"
    implementation "org.springframework.boot:spring-boot-starter-flyway"
    runtimeOnly    "org.flywaydb:flyway-database-postgresql"

    implementation "org.springdoc:springdoc-openapi-starter-webmvc-ui:${springdocVersion}"

    implementation "org.springframework.kafka:spring-kafka"

    implementation "org.springframework.boot:spring-boot-starter-data-jpa"
    implementation "org.springframework.boot:spring-boot-starter-validation"

    implementation "org.springframework.boot:spring-boot-starter-webmvc"
    implementation "org.springframework.boot:spring-boot-starter-restclient"
    implementation 'org.springframework.boot:spring-boot-starter-actuator'
    implementation 'io.micrometer:micrometer-registry-prometheus'

    implementation "no.nav.security:token-validation-spring:${tokenSupportVersion}"
    implementation "no.nav.security:token-client-core:${tokenSupportVersion}"
    implementation "no.nav.security:token-client-spring:${tokenSupportVersion}"

    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testImplementation 'org.springframework.boot:spring-boot-starter-webmvc-test'
    testImplementation 'org.springframework.boot:spring-boot-starter-data-jpa-test'
    testImplementation "com.h2database:h2"
    testImplementation "no.nav.security:token-validation-spring-test:${tokenSupportVersion}"
    testImplementation "no.nav.security:mock-oauth2-server"
    testImplementation "org.mockito.kotlin:mockito-kotlin:6.4.0"
    testRuntimeOnly "org.junit.platform:junit-platform-launcher"
}

application {
    mainClass = "no.nav.cv.eures.ApplicationKt"
}

test {
    useJUnitPlatform()
    testLogging {
        exceptionFormat = 'full'
    }
}

tasks.withType(KotlinCompile).configureEach {
    compilerOptions {
        jvmTarget = JvmTarget.JVM_25
        javaParameters = true
    }
}

tasks.withType(JavaExec) {
    classpath += test.classpath
    jvmArgs('-XX:TieredStopAtLevel=1', '-Dcom.sun.management.jmxremote')
}

tasks.jar { enabled = false }
