apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: pam-eures-cv-eksport
  namespace: teampam
  labels:
    team: teampam
spec:
  image: {{ image }}
  port: 9030
  liveness:
    path: /pam-eures-cv-eksport/internal/isAlive
    initialDelay: 60
  readiness:
    path: /pam-eures-cv-eksport/internal/isReady
    initialDelay: 60
  replicas:
    min: 1
    max: 1
  cpuThresholdPercentage: 50
  resources:
    limits:
      cpu: 1000m
      memory: 2048Mi
    requests:
      cpu: 200m
      memory: 512Mi
  accessPolicy:
    outbound:
      external:
        - host: {{ kafka_schema_registry }}
    inbound:
      rules:
        - application: pam-eures-cv-eksport-proxy
        - application: pam-personbruker
        - application: pam-cv
  webproxy: false
  envFrom:
    - secret: pam-eures-cv-eksport-secret
    - configmap: loginservice-idporten
  gcp:
    sqlInstances:
      - type: POSTGRES_11
        tier: {{ cloudsql_db_tier }}
        diskAutoresize: true
        diskType: SSD
        highAvailability: true
        databases:
          - name: pam-eures-cv-eksport
            envVarPrefix: DB
  prometheus:
    enabled: true
    path: /pam-eures-cv-eksport/actuator/prometheus
  env:
    - name: KAFKA_CONSUMER_TOPIC_CV_ENDRET
      value: {{ kafka_consumer_topic_cv_endret }}
    - name: KAFKA_BOOTSTRAP_SERVERS
      value: {{ kafka_bootstrap_servers }}
    - name: DB_DRIVER
      value: 'org.postgresql.Driver'
    - name: KAFKA_SCHEMA_REGISTRY
      value: {{ kafka_schema_registry }}
    - name: KAFKA_SECURITY_PROTOCOL
      value: SASL_SSL
    - name: AVRO_VERSION_FIFTYTWO_HEX
      value: {{ avro_version_fiftytwo_hex }}
  ingresses:
  {{#each ingress as |url|}}
     - {{url}}
  {{/each}}