apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: pam-eures-cv-eksport
  namespace: teampam
  labels:
    team: teampam
spec:
  image: {{ image }}
  port: 9030
  liveness:
    path: /pam-eures-cv-eksport/internal/isAlive
    initialDelay: 60
  readiness:
    path: /pam-eures-cv-eksport/internal/isReady
    initialDelay: 60
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 50
  resources:
    limits:
      cpu: 1000m
      memory: 2048Mi
    requests:
      cpu: 200m
      memory: 1024Mi
  accessPolicy:
    inbound:
      rules:
        - application: pam-personbruker
        - application: cv
    outbound:
      external:
        - host: {{ pdl_host }}
  webproxy: false
  envFrom:
    - secret: pam-eures-cv-eksport-secret
  azure:
    application:
      enabled: true
      tenant: {{ azure_ad_tenant }}
  tokenx:
    enabled: true
  gcp:
    sqlInstances:
      - type: POSTGRES_14
        tier: {{ cloudsql_db_tier }}
        diskAutoresize: true
        diskType: SSD
        highAvailability: true
        databases:
          - name: pam-eures-cv-eksport
            envVarPrefix: DB
  prometheus:
    enabled: true
    path: /pam-eures-cv-eksport/actuator/prometheus
  observability:
    logging:
      destinations:
        - id: loki
        - id: elastic
  env:
    - name: KAFKA_CONSUMER_TOPIC_CV_ENDRET_INTERN
      value: {{ kafka_consumer_topic_cv_endret_intern }}
    - name: DB_DRIVER
      value: 'org.postgresql.Driver'
    - name: PDL_SCOPE
      value: {{ pdl_scope }}
    - name: PDL_BASE_URL
      value: {{ pdl_base_url }}
    - name: SWAGGER_ENABLED
      value: "{{ swagger_enabled }}"
  ingresses:
  {{#each ingress as |url|}}
     - {{url}}
  {{/each}}
  kafka:
    pool: {{kafka_pool}}
