CREATE SEQUENCE CV_SEQ;

CREATE TABLE CV (
    ID              NUMERIC(19,0) NOT NULL PRIMARY KEY,
    AKTOR_ID        VARCHAR(36) NOT NULL,
    SIST_ENDRET     TIMESTAMP,
    RAW_AVRO        VARCHAR(128000) NOT NULL
);

CREATE INDEX IX_CV_AKTOR_ID
    ON CV (AKTOR_ID);