CREATE SEQUENCE CV_RAW_SEQ;

CREATE TABLE CV_RAW(
    ID             NUMERIC(19, 0)  NOT NULL PRIMARY KEY,
    AKTOER_ID      VARCHAR(36)     NOT NULL,
    FOEDSELSNUMMER VARCHAR(36)     NOT NULL,
    SIST_ENDRET    TIMESTAMP,
    RAW_AVRO       VARCHAR(128000) NOT NULL,
    PROSESSERT     BOOLEAN         NOT NULL DEFAULT FALSE,
    CONSTRAINT CV_RAW_UNIQUE_FOEDSELSNUMMER UNIQUE (FOEDSELSNUMMER),
    CONSTRAINT CV_RAW_UNIQUE_AKTOER_ID UNIQUE (AKTOER_ID)
);

CREATE INDEX IX_CV_RAW_FOEDSELSNUMMER
    ON CV_RAW (FOEDSELSNUMMER);