CREATE SEQUENCE CV_XML_SEQ;

CREATE TABLE CV_XML(
    ID             NUMERIC(19, 0)  NOT NULL PRIMARY KEY,
    FOEDSELSNUMMER VARCHAR(36)     NOT NULL,
    REFERANSE      VARCHAR(200),
    XML            VARCHAR(128000) NOT NULL,
    OPPRETTET      TIMESTAMP,
    SIST_ENDRET    TIMESTAMP,
    SLETTET        TIMESTAMP,
    CONSTRAINT CV_XML_UNIQUE_FOEDSELSNUMMER UNIQUE (FOEDSELSNUMMER)
);

CREATE INDEX IX_CV_XML_FOEDSELSNUMMER
    ON CV_XML (FOEDSELSNUMMER);