CREATE SEQUENCE SAMTYKKE_SEQ;

CREATE TABLE SAMTYKKE(
    ID                  NUMERIC(19, 0) NOT NULL PRIMARY KEY,
    FOEDSELSNUMMER      VARCHAR(36)    NOT NULL,
    SIST_ENDRET         TIMESTAMP,
    PERSONALIA          BOOLEAN        NOT NULL,
    UTDANNING           BOOLEAN        NOT NULL,
    FAGBREV             BOOLEAN        NOT NULL,
    ARBEIDSERFARING     BOOLEAN        NOT NULL,
    ANNEN_ERFARING      BOOLEAN        NOT NULL,
    FOERERKORT          BOOLEAN        NOT NULL,
    LOVREGULERTE_YRKER  BOOLEAN        NOT NULL,
    ANDRE_GODKJENNINGER BOOLEAN        NOT NULL,
    KURS                BOOLEAN        NOT NULL,
    SPRAAK              BOOLEAN        NOT NULL,
    SAMMENDRAG          BOOLEAN        NOT NULL,

    CONSTRAINT SAMTYKKE_UNIQUE_FOEDSELSNUMMER UNIQUE (FOEDSELSNUMMER)
);

CREATE INDEX IX_SAMTYKKE_FOEDSELSNUMMER
    ON SAMTYKKE (FOEDSELSNUMMER);

