CREATE TABLE CV_RAW
AS SELECT * FROM CV;

CREATE INDEX IX_CV_RAW_AKTOR_ID
    ON CV_RAW (AKTOR_ID);

DROP TABLE CV;

CREATE TABLE CV_XML (
    ID              NUMERIC(19,0) NOT NULL PRIMARY KEY,
    AKTOR_ID        VARCHAR(36) NOT NULL,
    SIST_ENDRET     TIMESTAMP,
    XML             VARCHAR(128000) NOT NULL
);

CREATE INDEX IX_CV_XML_AKTOR_ID
    ON CV_XML (AKTOR_ID);