ALTER TABLE CV_RAW
    ADD COLUMN AKTOER_ID VARCHAR(36) NOT NULL;

ALTER TABLE CV_RAW
ADD CONSTRAINT UNIQUE_AKTOER_ID_RAW
UNIQUE (AKTOER_ID);

UPDATE CV_RAW
    SET AKTOER_ID = AKTOR_ID;

ALTER TABLE CV_RAW
    DROP COLUMN AKTOR_ID;

CREATE INDEX IX_CV_RAW_AKTOER_ID
    ON CV_RAW (AKTOER_ID);