CREATE SEQUENCE ESCO_CACHE_SEQ;

CREATE TABLE ESCO_CACHE (
    ID                NUMERIC(19, 0)  NOT NULL PRIMARY KEY,
    TERM              VARCHAR(100)     NOT NULL,
    CONCEPT_ID        VARCHAR(10)     NOT NULL,
    ESCO              VARCHAR(100)     NOT NULL,
    UPDATED           TIMESTAMP);

CREATE INDEX IX_ESCO_CACHE_TERM
    ON ESCO_CACHE (TERM);

