ALTER TABLE CV_XML
    ADD COLUMN AKTOER_ID VARCHAR(36) NOT NULL;

ALTER TABLE CV_XML
ADD CONSTRAINT UNIQUE_AKTOER_ID_XML
UNIQUE (AKTOER_ID);

UPDATE CV_XML
    SET AKTOER_ID = AKTOR_ID;

ALTER TABLE CV_XML
    DROP COLUMN AKTOR_ID;

CREATE INDEX IX_CV_XML_AKTOER_ID
    ON CV_XML (AKTOER_ID);