CREATE SEQUENCE SAMTYKKE_SEQ;

CREATE TABLE SAMTYKKE (
    ID              NUMERIC(19,0) NOT NULL PRIMARY KEY,
    AKTOR_ID        VARCHAR(36) NOT NULL,
    SIST_ENDRET     TIMESTAMP,
    PERSONALIA      NUMERIC(1),
    UTDANNING       NUMERIC(1)
);

CREATE INDEX IX_SAMTYKKE_AKTOR_ID
    ON SAMTYKKE (AKTOR_ID);