CREATE SEQUENCE SAMTYKKE_SEQ;

CREATE TABLE SAMTYKKE (
    ID              NUMERIC(19,0) NOT NULL PRIMARY KEY,
    AKTOER_ID       VARCHAR(36) NOT NULL,
    SIST_ENDRET     TIMESTAMP,
    PERSONALIA      BOOLEAN NOT NULL,
    UTDANNING       BOOLEAN NOT NULL
);

CREATE INDEX IX_SAMTYKKE_AKTOER_ID
    ON SAMTYKKE (AKTOER_ID);