CREATE SEQUENCE SAMTYKKE_SEQ;

CREATE TABLE SAMTYKKE (
    ID              NUMERIC(19,0) NOT NULL PRIMARY KEY,
    AKTOER_ID       VARCHAR(36) NOT NULL,
    SIST_ENDRET     TIMESTAMP,
    PERSONALIA      NUMERIC(1),
    UTDANNING       NUMERIC(1)
);

CREATE INDEX IX_SAMTYKKE_AKTOER_ID
    ON SAMTYKKE (AKTOER_ID);