ALTER TABLE SAMTYKKE
ADD COLUMN FAGBREV NUMERIC(1);

ALTER TABLE SAMTYKKE
ADD COLUMN ARBEIDSERFARING NUMERIC(1);

ALTER TABLE SAMTYKKE
ADD COLUMN ANNEN_ERFARING NUMERIC(1);

ALTER TABLE SAMTYKKE
ADD COLUMN FOERERKORT NUMERIC(1);

ALTER TABLE SAMTYKKE
ADD COLUMN LOVREGULERTE_YRKER NUMERIC(1);

ALTER TABLE SAMTYKKE
ADD COLUMN ANDRE_GODKJENNINGER NUMERIC(1);

ALTER TABLE SAMTYKKE
ADD COLUMN KURS NUMERIC(1);

ALTER TABLE SAMTYKKE
ADD COLUMN SPRAAK NUMERIC(1);

ALTER TABLE SAMTYKKE
ADD COLUMN SAMMENDRAG NUMERIC(1);