ALTER TABLE SAMTYKKE
ADD COLUMN FAGBREV BOOLEAN NOT NULL;

ALTER TABLE SAMTYKKE
ADD COLUMN ARBEIDSERFARING BOOLEAN NOT NULL;

ALTER TABLE SAMTYKKE
ADD COLUMN ANNEN_ERFARING BOOLEAN NOT NULL;

ALTER TABLE SAMTYKKE
ADD COLUMN FOERERKORT BOOLEAN NOT NULL;

ALTER TABLE SAMTYKKE
ADD COLUMN LOVREGULERTE_YRKER BOOLEAN NOT NULL;

ALTER TABLE SAMTYKKE
ADD COLUMN ANDRE_GODKJENNINGER BOOLEAN NOT NULL;

ALTER TABLE SAMTYKKE
ADD COLUMN KURS BOOLEAN NOT NULL;

ALTER TABLE SAMTYKKE
ADD COLUMN SPRAAK BOOLEAN NOT NULL;

ALTER TABLE SAMTYKKE
ADD COLUMN SAMMENDRAG BOOLEAN NOT NULL;