DROP INDEX IX_ESCO_CACHE_TERM;

DROP TABLE ESCO_CACHE;

CREATE TABLE ESCO_CACHE (
    ID                NUMERIC(19, 0)  NOT NULL PRIMARY KEY,
    TERM              VARCHAR(1000)     NOT NULL,
    CONCEPT_ID        VARCHAR(100)     NOT NULL,
    ESCO              VARCHAR(1000)     NOT NULL,
    UPDATED           TIMESTAMP);

CREATE INDEX IX_ESCO_CACHE_TERM
    ON ESCO_CACHE (TERM);