ALTER TABLE SAMTYKKE
    ALTER COLUMN PERSONALIA TYPE BOOLEAN;

ALTER TABLE SAMTYKKE
    ALTER COLUMN UTDANNING TYPE BOOLEAN;

ALTER TABLE SAMTYKKE
    ALTER COLUMN FAGBREV TYPE BOOLEAN;

ALTER TABLE SAMTYKKE
    ALTER COLUMN ARBEIDSERFARING TYPE BOOLEAN;

ALTER TABLE SAMTYKKE
    ALTER COLUMN ANNEN_ERFARING TYPE BOOLEAN;

ALTER TABLE SAMTYKKE
    ALTER COLUMN FOERERKORT TYPE BOOLEAN;

ALTER TABLE SAMTYKKE
    ALTER COLUMN LOVREGULERTE_YRKER TYPE BOOLEAN;

ALTER TABLE SAMTYKKE
    ALTER COLUMN ANDRE_GODKJENNINGER TYPE BOOLEAN;

ALTER TABLE SAMTYKKE
    ALTER COLUMN KURS TYPE BOOLEAN;

ALTER TABLE SAMTYKKE
    ALTER COLUMN SPRAAK TYPE BOOLEAN;

ALTER TABLE SAMTYKKE
    ALTER COLUMN SAMMENDRAG TYPE BOOLEAN;
