spring:
  kafka:
    bootstrap-servers:
      - ${KAFKA_HOST:localhost}:9092
    properties:
      sasl:
        mechanism: PLAIN
        jaas:
          config: ''
      schema:
        registry:
          url: http://${KAFKA_HOST:localhost}:8081
      security:
        protocol: PLAINTEXT

kafka:
  topics:
    consumers:
      cv_endret: "arbeid-pam-cv-endret-v2-dev"


