spring:

  datasource:
    driverClassName: 'org.h2.Driver'
    url: 'jdbc:h2:mem:pam_eures_cv_eksport;MODE=PostgreSQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE'
    username: 'sa'
    password: ''

no.nav.security.jwt:
  expirythreshold: 1 #threshold in minutes until token expires
  issuer:
    selvbetjening:
      discoveryurl: http://localhost:${mock-oauth2-server.port}/selvbetjening/.well-known/openid-configuration
      acceptedaudience: aud-localhost
      cookiename: selvbetjening-idtoken