kafka:
  brokers:
    cv_endret: "192.168.99.100:9092"
  topics:
    consumers:
      cv_endret: "arbeid-pam-cv-endret-v2-dev"
  schema.registry.url: http://192.168.99.100:8081

datasources:
  default:
    connectionTestQuery: "select 1"
    jdbcUrl: "jdbc:postgresql://localhost:5432/pam-eures-cv-eksport"
    driverClassName: 'org.postgresql.Driver'