kafka:
  topics:
    consumers:
      cv_endret:  "test-topic"

datasources:
  default:
    url: 'jdbc:h2:mem:pam_eures_cv_eksport;MODE=PostgreSQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE'
    username: 'sa'
    password: ''
    driverClassName: 'org.h2.Driver'

flyway:
  datasources:
    default:
      locations: classpath:db
      initSql:
        - ''
      connection-init-sqls:
        - 'SET ROLE "pam-brukernotifikasjon-admin"'