micronaut:
  application:
    name: eures-cv-eksport
  server:
    context-path: /pam-eures-cv-eksport
    port: 9030

kafka:
  max:
    poll:
      records: 200
  reset-offset: false
  consumers:
    pam-eures-cv-eksport-v1:
      key:
        deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value:
        deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer
  bootstrap:
    servers:
      - 10.183.160.26:8443
      - 10.183.32.47:8443
      - 10.183.32.48:8443
  topics:
    consumers:
      cv_endret:  ${KAFKA_CONSUMER_TOPIC_CV_ENDRET}
      group_id: "pam-cv-eures-cv-eksport-v4"
  health:
    enabled: false
  security:
    protocol: SASL_SSL
  sasl:
    jaas:
      config: 'org.apache.kafka.common.security.plain.PlainLoginModule required username=${KAFKA_SERVICE_USER} password=${KAFKA_SERVICE_PASSWORD};'
    mechanism: PLAIN
  ssl:
    truststore:
      location: ${NAV_TRUSTSTORE_PATH}
      password: ${NAV_TRUSTSTORE_PASSWORD}
  schema.registry.url: http://kafka-schema-registry.tpa:8081

avro:
  schema.subject: "arbeid-pam-cv-endret-v2-dev-value"

db:
  vault:
    path: ${DB_VAULT_PATH:`postgresql/preprod`}
    username: ${DB_VAULT_USERNAME:`pam-eures-cv-eksport-admin`}

jpa:
  default:
    packages-to-scan:
      - 'no.nav.cv.eures.cv'
      - 'no.nav.cv.eures.samtykke'
    properties:
      hibernate:
        hbm2ddl:
          auto: none
        show_sql: false


datasources:
  default:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_DATABASE}
    driverClassName: ${DB_DRIVER:org.h2.Driver}
    username: ${DB_USERNAME:sa}
    password: ${DB_PASSWORD:''}
    maximum-pool-size: 2
    minimum-idle: 0
    pool-name: default
    connectionTestQuery: "select 1"

flyway:
  datasources:
    default:
      locations: classpath:db

jackson:
  serializationInclusion: ALWAYS
