kafka:
  bootstrap:
    servers:
      - ${KAFKA_HOST}:9092
  topics:
    consumers:
      cv_endret: "arbeid-pam-cv-endret-v2-dev"
  health:
    enabled: false
  security:
    protocol:
  sasl:
    jaas:
      config:
    mechanism:
  ssl:
    truststore:
      location:
      password:
  schema.registry.url: http://${KAFKA_HOST}:8081

datasources:
  default:
    url: 'jdbc:h2:mem:pam_eures_cv_eksport;MODE=PostgreSQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE'
    username: 'sa'
    password: ''
    driverClassName: 'org.h2.Driver'