micronaut:
  application:
    name: eures-cv-eksport
  server:
    context-path: /pam-eures-cv-eksport
    port: 9030

kafka:
  bootstrap:
    servers:
      - 10.183.160.26:8443
      - 10.183.32.47:8443
      - 10.183.32.48:8443
  topics:
    consumers:
      cv_endret:  ${KAFKA_CONSUMER_TOPIC_CV_ENDRET}
      group_id: "pam-cv-eures-cv-eksport-v1"
  health:
    enabled: false
  security:
    protocol: SASL_SSL
  sasl:
    jaas:
      config: 'org.apache.kafka.common.security.plain.PlainLoginModule required username=${KAFKA_USER} password=${KAFKA_PWD};'
    mechanism: PLAIN
  ssl:
    truststore:
      location: ${NAV_TRUSTSTORE_PATH}
      password: ${NAV_TRUSTSTORE_PASSWORD}
  schema.registry.url: http://${KAFKA_HOST_IP:localhost}:${SCHEMA_REGISTRY_PORT}

db:
  vault:
    path: ${DB_VAULT_PATH:`postgresql/preprod`}
    username: ${DB_VAULT_USERNAME:`pam-eures-cv-eksport-admin`}

jpa:
  default:
    packages-to-scan:
      - 'no.nav.cv.eures.cv'
    properties:
      hibernate:
        hbm2ddl:
          auto: none
        show_sql: false

datasources:
  default:
    minimumIdle: 0
    maximumPoolSize: 4
    idleTimeout: 10001
    maxLifetime: 30001
    connectionTestQuery: "select 1"
    jdbcUrl: ${JDBC_URL:`jdbc:postgresql://localhost:5432/pam-eures-cv-eksport`}
    driverClassName: 'org.postgresql.Driver'

flyway:
  datasources:
    default:
      locations: classpath:db
      initSql:
        - 'SET ROLE "pam-eures-cv-eksport-admin"'
