spring:

  datasource:
    driverClassName: 'org.h2.Driver'
    url: 'jdbc:h2:mem:pam_eures_cv_eksport;MODE=PostgreSQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE'
    username: 'sa'
    password: ''
    hikari:
      maximum-pool-size: 2
      minimum-idle: 0
      pool-name: default
no.nav.security.jwt.issuer:
  selvbetjening:
    cookie_name: localhost-idtoken

