management:
  endpoint.health.enabled: true
  endpoints:
    prometheus.enabled: true
    prometheus.web.enabled: true
    web.exposure.include: health,info,status,metrics,prometheus,configprops,env,conditions,beans,auditevents,mappings
  metrics:
    web.server.auto-time-requests: true
    distribution.percentiles-histogram.http.server.requests: true
    distribution.percentiles-histogram.http.client.requests: true
spring:
  metrics.web.server.auto-time-requests: true
  main:
    banner-mode: "off"
    allow-bean-definition-overriding: true
  profiles:
    active: ${NAIS_CLUSTER_NAME:dev}
  datasource:
    driverClassName: org.postgresql.Driver
    username: sa
    password:
