kafka:
  reset-offset: false
  topics:
    consumers:
      cv_endret:  "test-topic"
  security:
    protocol: PLAINTEXT
  sasl:
    jaas:
      config: ''
    mechanism: PLAIN
  ssl:
    truststore:
      location: ''
      password: ''
  schema:
    registry:
      url: http://${KAFKA_HOST:localhost}:8081

datasources:
  default:
    url: 'jdbc:h2:mem:pam_eures_cv_eksport;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE'
    username: 'sa'
    password: ''
    driverClassName: 'org.h2.Driver'

flyway:
  datasources:
    default:
      locations: classpath:db
      initSql:
        - ''
      connection-init-sqls:
        - 'SET ROLE "pam-brukernotifikasjon-admin"'