server:
  port: 9030
  servlet:
    context-path: /pam-eures-cv-eksport

spring:
  kafka:
    consumer:
      group-id: pam-eures-cv-eksport-v1
      auto-offset-reset: earliest
  datasource:
    driver-class-name: ${DB_DRIVER:org.postgresql.Driver}
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_DATABASE:pam-eures-cv-eksport}
    username: ${DB_USERNAME:pam-eures-cv-eksport-admin}
    password: ${DB_PASSWORD:''}
    hikari:
      maximum-pool-size: 2
      minimum-idle: 0
      pool-name: default
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations:
      - "classpath:db"
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
      dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false


kafka:
  max:
    poll:
      records: 200
  reset-offset: false
  consumers:
    pam-eures-cv-eksport-v1:
      key:
        deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value:
        deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer
  bootstrap:
    servers:
      - 10.183.160.26:8443
      - 10.183.32.47:8443
      - 10.183.32.48:8443
  topics:
    consumers:
      cv_endret: ${KAFKA_CONSUMER_TOPIC_CV_ENDRET}
  health:
    enabled: false
  security:
    protocol: SASL_SSL
  sasl:
    jaas:
      config: 'org.apache.kafka.common.security.plain.PlainLoginModule required username=${KAFKA_SERVICE_USER} password=${KAFKA_SERVICE_PASSWORD};'
    mechanism: PLAIN
  ssl:
    truststore:
      location: ${NAV_TRUSTSTORE_PATH}
      password: ${NAV_TRUSTSTORE_PASSWORD}
  schema.registry.url: http://kafka-schema-registry.tpa:8081

avro:
  schema.subject: "arbeid-pam-cv-endret-v2-dev-value"

jackson:
  serializationInclusion: ALWAYS
