name: deploy-prod
on:
  release:
    types: [published]

jobs:
  call-workflow:
    permissions:
      contents: write
      id-token: write
    uses: navikt/pam-deploy/.github/workflows/deploy-prod.yml@v7
    with:
      NAIS_RESOURCE: naiserator.yml
