name: build-deploy-dev
on:
  push:
    paths-ignore:
      - "**.md"
      - ".gitignore"
      - "LICENCE"
      - "CODEOWNERS"
    branches:
      - "**"
      - feature

jobs:
  call-workflow:
    permissions:
      actions: read
      contents: write
      id-token: write
      security-events: write
    if: "(github.ref_name == 'master') || contains(github.event.head_commit.message, 'deploy:dev') || contains(github.ref, 'feature/')"
    uses: navikt/pam-deploy/.github/workflows/deploy-dev.yml@v7
    with:
      NAIS_RESOURCE: naiserator.yml
      JAVA_VERSION: "18"
      SKIP_DRAFT_RELEASE: ${{ github.ref_name != 'master' }}
    secrets:
      NAIS_WORKLOAD_IDENTITY_PROVIDER: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
