name: build-deploy-dev
on:
  push:
    paths-ignore:
      - "**.md"
      - ".gitignore"
      - "LICENCE"
      - "CODEOWNERS"
    branches:
      - master
      - nytt-cv-topic-feilsoking

jobs:
  call-workflow:
    uses: navikt/pam-deploy/.github/workflows/deploy-dev.yml@v2
    with:
      NAIS_RESOURCE: naiserator.yml
      SNYK_ENABLED: false
      JAVA_VERSION: "18"
    secrets:
      NAIS_DEPLOY_APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
